# Generated by Django 5.1.4 on 2026-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetmonth',
            name='total_money',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
