# Generated by Django 5.1.4 on 2026-08-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_add_period_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('period_1', 'Days 1-10'), ('period_2', 'Days 11-20'), ('period_3', 'Days 21-end'), ('monthly_full', 'Monthly Full Report')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='budget.budgetmonth')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('budget_month', 'report_type'), name='uq_budget_month_report_email')],
            },
        ),
    ]
