# Generated by Django 6.1 on 2026-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_pocketuser_auth_user_balance_budgetmonth_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemaillog',
            name='report_type',
            field=models.CharField(choices=[('period_1', 'Days 1-10'), ('period_2', 'Days 11-20'), ('period_3', 'Days 21-end'), ('monthly_full', 'Monthly Full Report'), ('category', 'Category Report')], max_length=20),
        ),
    ]
