"""Email service for sending budget reports to users."""

import logging

from django.conf import settings
from django.core.mail import EmailMultiAlternatives

from budget.currency import format_mmk
from budget.services.report_service import MonthlyReport

logger = logging.getLogger(__name__)

def _from_email() -> str:
    """Return the from-email with the display name 'Pocket Management System'."""
    raw = settings.DEFAULT_FROM_EMAIL or settings.EMAIL_HOST_USER
    sender_name = getattr(settings, "EMAIL_FROM_NAME", "Pocket Management System")
    return f"{sender_name} <{raw}>"


def _build_report_html(report: MonthlyReport, user_name: str) -> str:
    month_name = settings.MONTH_NAMES[report.month]

    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #2563eb;">Pocket Money Report</h1>
    <p>Hello <strong>{user_name}</strong>,</p>
    <p>Here is your budget report for <strong>{month_name} {report.year}</strong>.</p>

    <div style="background: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <h2 style="margin-top: 0;">Monthly Summary</h2>
        <table style="width: 100%; border-collapse: collapse;">
             <tr><td>Total Money Available</td><td style="text-align:right;"><strong>{format_mmk(report.total_money)}</strong></td></tr>
            <tr><td>Adjusted Available Money</td><td style="text-align:right;"><strong>{format_mmk(report.adjusted_total_money)}</strong></td></tr>
            <tr><td>Total Budget Estimated</td><td style="text-align:right;">{format_mmk(report.total_budget_estimated)}</td></tr>
            <tr><td>Total Actually Spent</td><td style="text-align:right;">{format_mmk(report.total_actual_spent)}</td></tr>
            <tr style="font-size: 1.1em; color: {'#2563eb' if report.remaining_balance >= 0 else '#dc2626'};">
                <td><strong>Remaining Balance</strong></td>
                <td style="text-align:right;"><strong>{format_mmk(report.remaining_balance)}</strong></td>
            </tr>
            <tr style="font-size: 1.2em; color: {'#16a34a' if report.overall_status == 'surplus' else '#dc2626'};">
                <td><strong>Overall {report.overall_status.title()}</strong></td>
                <td style="text-align:right;"><strong>{format_mmk(report.overall_difference)}</strong></td>
            </tr>
        </table>
    </div>

    <h2>Category Comparison (Budget vs Actual)</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
        <tr style="background: #e5e7eb;">
            <th style="padding: 8px; text-align: left;">Category</th>
            <th style="padding: 8px; text-align: right;">Budget</th>
            <th style="padding: 8px; text-align: right;">Actual</th>
            <th style="padding: 8px; text-align: right;">Status</th>
            <th style="padding: 8px; text-align: right;">Amount</th>
        </tr>
    """

    for item in report.period_reports:
        color = "#16a34a" if item.status == "surplus" else "#dc2626"
        range_label = ""
        if item.start_day is not None and item.end_day is not None:
            range_label = f" (Day {item.start_day}-{item.end_day})"
        html += f"""
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">{item.category_name}{range_label}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.budget_amount)}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.actual_amount)}</td>
            <td style="padding: 8px; text-align: right; color: {color}; border-bottom: 1px solid #e5e7eb;">{item.status.title()}</td>
            <td style="padding: 8px; text-align: right; color: {color}; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.difference)}</td>
        </tr>
        """

    if report.zero_spend_periods:
        html += """
        <div style="background: #fefce8; padding: 16px; border-radius: 8px; margin: 16px 0; border: 1px solid #fde047;">
            <h3 style="margin-top: 0; color: #854d0e;">No Spending Periods</h3>
            <p style="margin: 0; color: #713f12;">
                No money was spent in: <strong>{periods}</strong>.<br>
                The budget for these periods has been added back to your available money.
            </p>
        </div>
        """.format(periods=", ".join(report.zero_spend_periods))

    html += """
    </table>
    <p style="color: #6b7280; font-size: 0.9em; margin-top: 32px;">
        This report was generated by Pocket Money Management System.
    </p>
    </body></html>
    """
    return html


def _send_email(to_email: str, subject: str, html_content: str) -> bool:
    """Send an HTML email. Returns True on success."""
    if not settings.EMAIL_HOST_USER or not settings.EMAIL_HOST_PASSWORD:
        logger.warning("SMTP not configured. Skipping email send.")
        return False

    try:
        msg = EmailMultiAlternatives(
            subject=subject,
            body="Your pocket money report is attached as HTML.",
            from_email=_from_email(),
            to=[to_email],
        )
        msg.attach_alternative(html_content, "text/html")
        msg.send(fail_silently=False)
        logger.info("Email sent to %s", to_email)
        return True
    except Exception:
        logger.exception("Failed to send email to %s", to_email)
        return False


def send_report_email(to_email: str, user_name: str, report: MonthlyReport) -> bool:
    """Send the full monthly report via email. Returns True on success."""
    month_name = settings.MONTH_NAMES[report.month]
    subject = f"Pocket Money Report - {month_name} {report.year}"
    html_content = _build_report_html(report, user_name)
    return _send_email(to_email, subject, html_content)


def send_monthly_report_email(to_email: str, user_name: str, report: MonthlyReport) -> bool:
    """Send the full monthly report via email (alias for send_report_email)."""
    return send_report_email(to_email, user_name, report)


def _build_category_html(
    category_name: str,
    budget,
    actual,
    user_name: str,
) -> str:
    """Build a budget-vs-actual HTML email for one category."""
    difference = budget - actual
    color = "#16a34a" if difference >= 0 else "#dc2626"

    return f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #2563eb;">Pocket Money Report — {category_name}</h1>
    <p>Hello <strong>{user_name}</strong>,</p>
    <p>You have recorded spending in your <strong>{category_name}</strong>
    category. Here is its budget summary.</p>

    <div style="background: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <h2 style="margin-top: 0;">Category Summary</h2>
        <table style="width: 100%; border-collapse: collapse;">
            <tr><td>Estimated Budget</td><td style="text-align:right;"><strong>{format_mmk(budget)}</strong></td></tr>
            <tr><td>Total Actually Spent</td><td style="text-align:right;"><strong>{format_mmk(actual)}</strong></td></tr>
            <tr><td>Remaining</td><td style="text-align:right; color: {color};"><strong>{format_mmk(difference)}</strong></td></tr>
        </table>
    </div>

    <p style="color: #6b7280; font-size: 0.9em; margin-top: 32px;">
        This report was generated by Pocket Money Management System.
    </p>
    </body></html>
    """


def send_category_report_email(
    to_email: str,
    user_name: str,
    category_name: str,
    budget,
    actual,
) -> bool:
    """Send a single-category budget report via email."""
    subject = f"Pocket Money Report — {category_name}"
    html_content = _build_category_html(category_name, budget, actual, user_name)
    return _send_email(to_email, subject, html_content)
