"""Email service for sending budget reports to users."""

import logging

from django.conf import settings
from django.core.mail import EmailMultiAlternatives

from budget.currency import format_mmk
from budget.services.report_service import CategoryComparison, MonthlyReport

logger = logging.getLogger(__name__)

def _from_email() -> str:
    """Return the from-email with the display name 'Pocket Management System'."""
    raw = settings.DEFAULT_FROM_EMAIL or settings.EMAIL_HOST_USER
    sender_name = getattr(settings, "EMAIL_FROM_NAME", "Pocket Management System")
    return f"{sender_name} <{raw}>"


def _build_report_html(report: MonthlyReport, user_name: str) -> str:
    month_name = settings.MONTH_NAMES[report.month]

    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #2563eb;">Pocket Money Report</h1>
    <p>Hello <strong>{user_name}</strong>,</p>
    <p>Here is your budget report for <strong>{month_name} {report.year}</strong>.</p>

    <div style="background: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <h2 style="margin-top: 0;">Monthly Summary</h2>
        <table style="width: 100%; border-collapse: collapse;">
            <tr><td>Total Money Available</td><td style="text-align:right;"><strong>{format_mmk(report.total_money)}</strong></td></tr>
            <tr><td>Total Budget Estimated</td><td style="text-align:right;">{format_mmk(report.total_budget_estimated)}</td></tr>
            <tr><td>Total Actually Spent</td><td style="text-align:right;">{format_mmk(report.total_actual_spent)}</td></tr>
            <tr style="font-size: 1.2em; color: {'#16a34a' if report.overall_status == 'surplus' else '#dc2626'};">
                <td><strong>Overall {report.overall_status.title()}</strong></td>
                <td style="text-align:right;"><strong>{format_mmk(report.overall_difference)}</strong></td>
            </tr>
        </table>
    </div>

    <h2>Category Comparison (Budget vs Actual)</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
        <tr style="background: #e5e7eb;">
            <th style="padding: 8px; text-align: left;">Category</th>
            <th style="padding: 8px; text-align: right;">Budget</th>
            <th style="padding: 8px; text-align: right;">Actual</th>
            <th style="padding: 8px; text-align: right;">Status</th>
            <th style="padding: 8px; text-align: right;">Amount</th>
        </tr>
    """

    for item in report.period_reports:
        color = "#16a34a" if item.status == "surplus" else "#dc2626"
        range_label = ""
        if item.start_day is not None and item.end_day is not None:
            range_label = f" (Day {item.start_day}-{item.end_day})"
        html += f"""
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">{item.category_name}{range_label}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.budget_amount)}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.actual_amount)}</td>
            <td style="padding: 8px; text-align: right; color: {color}; border-bottom: 1px solid #e5e7eb;">{item.status.title()}</td>
            <td style="padding: 8px; text-align: right; color: {color}; border-bottom: 1px solid #e5e7eb;">{format_mmk(item.difference)}</td>
        </tr>
        """

    html += """
    </table>
    <p style="color: #6b7280; font-size: 0.9em; margin-top: 32px;">
        This report was generated by Pocket Money Management System.
    </p>
    </body></html>
    """
    return html


def _build_period_report_html(
    report: MonthlyReport, item: CategoryComparison, user_name: str
) -> str:
    """Build an HTML email for a single category (e.g. Days 1-10)."""
    month_name = settings.MONTH_NAMES[report.month]
    color = "#16a34a" if item.status == "surplus" else "#dc2626"
    range_label = ""
    if item.start_day is not None and item.end_day is not None:
        range_label = f" (Day {item.start_day}-{item.end_day})"

    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #2563eb;">Pocket Money Report</h1>
    <p>Hello <strong>{user_name}</strong>,</p>
    <p>Here is your budget report for <strong>{month_name} {report.year}</strong>.</p>

    <div style="background: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <h2 style="margin-top: 0;">{item.category_name}{range_label}</h2>
        <table style="width: 100%; border-collapse: collapse;">
            <tr><td>Budget Estimated</td><td style="text-align:right;">{format_mmk(item.budget_amount)}</td></tr>
            <tr><td>Actually Spent</td><td style="text-align:right;">{format_mmk(item.actual_amount)}</td></tr>
            <tr style="font-size: 1.2em; color: {color};">
                <td><strong>Status: {item.status.title()}</strong></td>
                <td style="text-align:right;"><strong>{format_mmk(item.difference)}</strong></td>
            </tr>
        </table>
    </div>

    <p style="color: #6b7280; font-size: 0.9em; margin-top: 32px;">
        This report was generated by Pocket Money Management System.
    </p>
    </body></html>
    """
    return html


def _send_email(to_email: str, subject: str, html_content: str) -> bool:
    """Send an HTML email. Returns True on success."""
    if not settings.EMAIL_HOST_USER or not settings.EMAIL_HOST_PASSWORD:
        logger.warning("SMTP not configured. Skipping email send.")
        return False

    try:
        msg = EmailMultiAlternatives(
            subject=subject,
            body="Your pocket money report is attached as HTML.",
            from_email=_from_email(),
            to=[to_email],
        )
        msg.attach_alternative(html_content, "text/html")
        msg.send(fail_silently=False)
        logger.info("Email sent to %s", to_email)
        return True
    except Exception:
        logger.exception("Failed to send email to %s", to_email)
        return False


def send_report_email(to_email: str, user_name: str, report: MonthlyReport) -> bool:
    """Send the full monthly report via email. Returns True on success."""
    month_name = settings.MONTH_NAMES[report.month]
    subject = f"Pocket Money Report - {month_name} {report.year}"
    html_content = _build_report_html(report, user_name)
    return _send_email(to_email, subject, html_content)


def send_monthly_report_email(to_email: str, user_name: str, report: MonthlyReport) -> bool:
    """Send the full monthly report via email (alias for send_report_email)."""
    return send_report_email(to_email, user_name, report)


def send_period_report_email(
    to_email: str,
    user_name: str,
    report: MonthlyReport,
    item: CategoryComparison,
    month_label: str,
) -> bool:
    """Send a single category report (e.g. Days 1-10) via email."""
    subject = f"Pocket Money Report - {item.category_name} ({month_label})"
    html_content = _build_period_report_html(report, item, user_name)
    return _send_email(to_email, subject, html_content)